# Generated by Django 6.0.6 on 2026-07-10 05:45

import apps.auth_core.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.auth_core.managers.UserManager()),
            ],
        ),
    ]
